import { Geist, Geist_Mono } from "next/font/google";
import { VT323, Share_Tech_Mono } from "next/font/google";
import "./globals.css";
import { FrameInit } from "@/components/FrameInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vt323 = VT323({
  weight: '400',
  variable: '--font-vt323',
  subsets: ['latin'],
});

const shareTechMono = Share_Tech_Mono({
  weight: '400',
  variable: '--font-share-tech-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${vt323.variable} ${shareTechMono.variable}`}>
        <div>
          {children}
          <FrameInit />
        </div>
      </body>
    </html>
  );
}
